### ISSUE TITLE
Suggestion: Abillity to use float values for offset

### ISSUE THREAD

**Issue by ghost** [bergerhealer/TC-HangRail#6]
### Description
In the description on spigotmc it says:
"Only integer values for the offsets are presently supported, so things like "2.6" are not possible here."

Now i would like to ask you to consider it in future updates to make this possible.

### Examples
Do you have any examples for where it could be used?
It would be very helpful with blocks which are not at full height.
Like the campfire for example.

Thank you.

**Comment by bbayu123** [comment]
Closing issue, will not be supported - please use TC-Coasters for more fine control.
